const SURVEY_CONFIG={url:'https://uibiwhkxlyxdfytvudbn.supabase.co/functions/v1/customer-survey',key:'sb_publishable_R-auhGcSmwSl-1U9WdGe3g_ZYm5BZEt'};
const SITES={puruchuco:'Real Plaza Puruchuco',salaverry:'Real Plaza Salaverry',primavera:'Real Plaza Primavera',civico:'Real Plaza Centro Cívico',gama:'GAMA'};
const QUESTIONS=[['atencion','La atención fue amable y respetuosa'],['uniforme','El uniforme, vestimenta y presentación fueron adecuados'],['saludo','La persona respondió el saludo y se mostró cordial'],['informacion','La información brindada fue clara y correcta'],['solucion','La orientación o solución respondió a tu consulta']];
const site=new URLSearchParams(location.search).get('sede')?.toLowerCase()||'';
const startedAt=Date.now();
const $=id=>document.getElementById(id);

async function request(body){const response=await fetch(SURVEY_CONFIG.url,{method:'POST',headers:{'Content-Type':'application/json',apikey:SURVEY_CONFIG.key,Authorization:`Bearer ${SURVEY_CONFIG.key}`},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok||data.error)throw new Error(data.error||'No se pudo conectar.');return data}
function renderQuestions(){const container=$('surveyQuestions');QUESTIONS.forEach(([key,label])=>{const section=document.createElement('section');section.className='survey-question';section.innerHTML=`<fieldset><legend>${label}</legend><div class="survey-options">${[['1','Cumple'],['0','No cumple'],['2','No aplica']].map(([value,text])=>`<label class="survey-option"><input type="radio" name="${key}" value="${value}" required><span>${text}</span></label>`).join('')}</div></fieldset>`;container.appendChild(section)})}
async function init(){if(!SITES[site]){$('surveySiteName').textContent='El QR no corresponde a una sede válida.';return}$('surveySiteName').textContent=SITES[site];renderQuestions();try{const data=await request({action:'staff',site});data.staff.forEach(person=>$('surveyStaff').add(new Option(person.name,person.id)));$('surveyForm').hidden=false}catch(error){$('surveySiteName').textContent=error.message}}
async function submit(event){event.preventDefault();const button=$('surveySubmit');button.disabled=true;$('surveyStatus').textContent='Enviando...';try{const form=new FormData(event.currentTarget);const answers=Object.fromEntries(QUESTIONS.map(([key])=>[key,Number(form.get(key))]));await request({action:'submit',site,collaboratorId:$('surveyStaff').value,answers,observation:$('surveyObservation').value,website:$('surveyWebsite').value,startedAt});$('surveyForm').hidden=true;$('surveyThanks').hidden=false}catch(error){$('surveyStatus').textContent=error.message;button.disabled=false}}
$('surveyForm').addEventListener('submit',submit);$('surveyAgain').addEventListener('click',()=>location.reload());init();
