create table if not exists public.push_delivery_logs (
    id bigint generated by default as identity primary key,
    evento text not null,
    sede text,
    remitente uuid references auth.users(id) on delete set null,
    destinatarios integer not null default 0,
    enviados integer not null default 0,
    fallidos integer not null default 0,
    detalle jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now()
);
alter table public.push_delivery_logs enable row level security;
drop policy if exists "push_logs_select_superior" on public.push_delivery_logs;
create policy "push_logs_select_superior" on public.push_delivery_logs for select to authenticated using (public.es_encargado_ti());
create index if not exists push_delivery_logs_fecha_idx on public.push_delivery_logs (created_at desc);
